{
 "title": "MongoDB Overview Hmx",
 "description": "mongoDB Overview compatible with percona mongodb exporter  and this docker \r\nhttps://hub.docker.com/r/eses/mongodb_exporter/\r\n",
 "tags": [
  "MongoDB",
  "Percona",
  "prometheus"
 ],
 "time": { "from": "2019-12-04T09:00:52.599Z", "to": "2019-12-04T21:00:52.599Z" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Instance",
    "query": "label_values(mongodb_mongod_connections, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Command Operations",
   "type": "graph",
   "description": "Shows how many times a command is executed per second on average during the selected interval.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{type!=\"command\"}[$interval]) or irate(mongodb_op_counters_total{type!=\"command\"}[5m])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "rate(mongodb_op_counters_repl_total{type!~\"(command|query|getmore)\"}[$interval]) or irate(mongodb_op_counters_repl_total{type!~\"(command|query|getmore)\"}[5m])",
     "legendFormat": "repl_{{type}}"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_ttl_deleted_documents_total[$interval]) or irate(mongodb_mongod_metrics_ttl_deleted_documents_total[5m])",
     "legendFormat": "ttl_delete"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Keep in mind the hard limit on the maximum number of connections set by your distribution.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_connections{state=\"current\"}",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Queued Operations",
   "type": "graph",
   "description": "Any number of queued operations for long periods of time is an indication of possible issues. Find the cause and fix it before requests get stuck in the queue.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_global_lock_current_queue",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "graph",
   "description": "When used in combination with 'Command Operations', this graph can help identify write amplification. For example, when one insert or update command actually inserts or updates hundreds, thousands, or even millions of documents.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_document_total[$interval]) or irate(mongodb_mongod_metrics_document_total[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Scanned and Moved Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total[$interval]) or irate(mongodb_mongod_metrics_query_executor_total[5m])",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_record_moves_total[$interval]) or irate(mongodb_mongod_metrics_record_moves_total[5m])",
     "legendFormat": "moved"
    }
   ]
  },
  {
   "title": "Query Efficiency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mongodb_mongod_metrics_query_executor_total{state=\"scanned_objects\"}[5m]))/sum(increase(mongodb_mongod_metrics_document_total{state=\"returned\"}[5m]))",
     "legendFormat": "Document"
    },
    {
     "expr": "sum(increase(mongodb_mongod_metrics_query_executor_total{state=\"scanned\"}[5m]))/sum(increase(mongodb_mongod_metrics_document_total{state=\"returned\"}[5m]))",
     "legendFormat": "Index"
    }
   ]
  },
  {
   "title": "getLastError Write Operations",
   "type": "graph",
   "description": "This is useful for write-heavy workloads to understand how long it takes to verify writes and how many concurrent writes are occurring.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_get_last_error_wtime_num_total[$interval]) or irate(mongodb_mongod_metrics_get_last_error_wtime_num_total[5m])",
     "legendFormat": "Total"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_get_last_error_wtimeouts_total[$interval]) or irate(mongodb_mongod_metrics_get_last_error_wtimeouts_total[5m])",
     "legendFormat": "Timeouts"
    }
   ]
  },
  {
   "title": "getLastError Write Time",
   "type": "graph",
   "description": "This is useful for write-heavy workloads to understand how long it takes to verify writes and how many concurrent writes are occurring.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_get_last_error_wtime_total_milliseconds[$interval]) or irate(mongodb_mongod_metrics_get_last_error_wtime_total_milliseconds[5m])",
     "legendFormat": "Write Wait Time"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "graph",
   "description": "Page faults indicate that requests are processed from disk either because an index is missing or there is not enough memory for the data set. Consider increasing memory or sharding out.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_extra_info_page_faults_total[$interval]) or irate(mongodb_extra_info_page_faults_total[5m])",
     "legendFormat": "Faults"
    }
   ]
  },
  {
   "title": "Assert Events",
   "type": "graph",
   "description": "Asserts are not important by themselves, but you can correlate spikes with other graphs.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_asserts_total[$interval]) or irate(mongodb_asserts_total[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}