global:
  resolve_timeout: 1m
route:
  receiver: custom
  group_by:
  - ManyRequests
  routes:
  - receiver:   custom
    continue: true
  group_wait: 1m
  group_interval: 5m
  repeat_interval: 1h
receivers:
- name: custom
  webhook_configs:
  - send_resolved: true
    url: 'https://pruu.herokuapp.com/dump/prom_test'