version: '3.4'

services:
  corecrudapi:
    image: fabricioveronez/corecrud
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: CoreCRUD/CoreCRUD.Api/Dockerfile
    networks:
      - corecrud

  corecrud-mongodb:
    image: mongo:4.1
    volumes:
      - db_mongo:/data/db
    networks:
      - corecrud
    restart: always
    command: --storageEngine wiredTiger
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: GPX4WOwpcvOc9Wm70gAG8It7tKA0Cy090ZVO82cEJsExogsMDY

  prometheus:
    image: prom/prometheus    
    volumes: 
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yaml:/etc/prometheus/alert.rules
    ports:
      - "9090:9090"
    depends_on:
      - corecrudapi
    networks:
      - corecrud
  
  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes: 
      - ./alertconfig.yaml:/etc/alertmanager/alertconfig.yml
    command:
      - '--config.file=/etc/alertmanager/alertconfig.yml'      
    depends_on:
      - prometheus
    networks:
      - corecrud      


  grafana:
    image: grafana/grafana:5.3.2     
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - corecrud

  mongoexporter:
    image: fabricioveronez/mongo_exporter
    ports:
      - "9216:9216" 
    networks:
      - corecrud
    environment: 
      MONGODB_URI: "mongodb://mongouser:GPX4WOwpcvOc9Wm70gAG8It7tKA0Cy090ZVO82cEJsExogsMDY@corecrud-mongodb:27017"    

volumes:
  db_mongo:
networks: 
  corecrud: 
    driver: bridge