# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

  external_labels:
    monitor: codelab

rule_files:
- "alert.rules"        

scrape_configs: 
  - job_name: 'appmetrics'
    
    scrape_interval: 5s   
    static_configs:
      - targets: ['corecrudapi:80']

  - job_name: 'prometheus'
        
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mongodb_exporter'
        
    scrape_interval: 5s          
    static_configs:    
      - targets: ['mongoexporter:9216']    

alerting:
  alertmanagers:
  - scheme: https
    static_configs:
    - targets:
      - "alertmanager:9093"
